### PR TITLE
Helper Class

### PR DESCRIPTION
**Pull request by fahadjamal**
Swift File

### CODE REVIEW

**Comment by profahad** [comment]
it will help us to easily achieve things in swift too

**Comment by blacksmoke26** [comment]
This may break few things! @fahadjamal 

Can you please double-check? @usama036 

Also check the BC (Backward compatibility) @profahad

**Comment by usama036** [comment]
working in issue

**Comment by fahadjamal** [comment]
sir kindly accept my pull request.

**Review by profahad — APPROVED** [review]
Overall looks great

**Comment by profahad** [comment]
Merging done

Thank you @fahadjamal

**Pull request merged**
